### ISSUE TITLE
Cleanliness of Code

### ISSUE THREAD

**Issue by Courtney513** [Valerie-Wissenburg/web-iv-portfolio-site#12]
overall your cleanliness of code is below statisfactory but that can be easily fixed.
You have some simple image-related errors on your pages like no alt tag or an empty src tag. You could change your "wrapper" ids and any other repeated ids into a class. li needs to be the child of the ul not anchor. `<i class="fi-social-facebook"><a href="#"> </a></i>` for example on line 160.
on line 68 remove the backslash and add the ending tag like this for example:
 `<a href="https://twitter.com/TwitterAccount" target="_blank" img src="https://www.someserver.ca/images/twitter.png" border="0"></a>`

on lines 30, 146, 181, 195, 204, and 213 when I ran your css through the validator it said you had 6 parse errors which has to do with spaces in your css. check out this article on how to fix them.
http://stackoverflow.com/questions/14111733/what-is-a-parse-error-and-how-do-i-fix-it

**Comment by e-m-durham** [comment]
Make sure you're using smart typography.
<img width="375" alt="screen shot 2015-11-14 at 10 32 28 am" src="https://cloud.githubusercontent.com/assets/2342978/11164612/165e5eaa-8abb-11e5-9d76-2f318307f94d.png">

**Comment by e-m-durham** [comment]
Errors in your CSS in the media queries `//` is not a CSS comment, also, make sure you eventually remove unused queries. 
<img width="204" alt="screen shot 2015-11-14 at 10 33 32 am" src="https://cloud.githubusercontent.com/assets/2342978/11164613/2f5816da-8abb-11e5-8400-9e4f7ea20c83.png">

**Comment by e-m-durham** [comment]
Use shorthand in CSS like `font` instead of defining `font-weight`, `font-size`, etc. separately. 
<img width="324" alt="screen shot 2015-11-14 at 10 34 42 am" src="https://cloud.githubusercontent.com/assets/2342978/11164623/72931012-8abb-11e5-90d4-f14a6df6e4a6.png">

**Comment by e-m-durham** [comment]
Begin a table of contents for your stylesheet.
