### ISSUE TITLE
Semantics

### ISSUE THREAD

**Issue by elladurham** [Valerie-Wissenburg/web-iv-portfolio-site#13]
Try not to use visual properties as class names like ".margin"-about-pictures it's better to name your classes semantically or find other ways to target those elements and let the visual properties be dictated by the CSS rule.

**Comment by e-m-durham** [comment]
Make sure you're alway using the appropriate html element for the job, like `<small>` for your copyright or span a class in the introduction to your paragraph like on line 39 of tokyo-identity.html
