### ISSUE TITLE
Directory Organization

### ISSUE THREAD

**Issue by drexnexlo** [Valerie-Wissenburg/web-iv-portfolio-site#4]
Nothing to say - totally fine up to this point. Advanced!

**Comment by e-m-durham** [comment]
Make sure you end up removing any script files that you don't end up using—dropdown.js, reveal.js, etc.

**Comment by e-m-durham** [comment]
Eventually consider the way you're naming files. In the future, you may have more than one ad campaign  or package design. Consider appending the client on that'd probably be a good convention. "ad-campaign-this-client.html" "ad-campaign-that-client.html"
